package com.haryobimo.paymentservice.models;

public enum PaymentMethodType {
    VIRTUAL_ACCOUNT_BCA,
    VIRTUAL_ACCOUNT_BANK_MANDIRI,
    VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI,
    VIRTUAL_ACCOUNT_DOKU,
    VIRTUAL_ACCOUNT_BRI,
    VIRTUAL_ACCOUNT_BNI,
    VIRTUAL_ACCOUNT_BANK_PERMATA,
    VIRTUAL_ACCOUNT_BANK_CIMB,
    VIRTUAL_ACCOUNT_BANK_DANAMON,
    ONLINE_TO_OFFLINE_ALFA,
    CREDIT_CARD,
    DIRECT_DEBIT_BRI,
    EMONEY_SHOPEEPAY,
    EMONEY_OVO,
    QRIS,
    PEER_TO_PEER_AKULAKU,
    PEER_TO_PEER_KREDIVO,
    PEER_TO_PEER_INDODANA
}

